name: PyLint Check

on:
  push:
    branches: [ main ]

jobs:
  pylint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to Latest Commit
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.x'
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Run PyLint
        run: |
          pylint **/*.py